---
- name: BUILD AND PUSH NETWORK CONFIGURATION FILES
  hosts: Routers
  connection: local
  gather_facts: no
  vars:
    un: "eric"
    pwd: "eric"
    os: "ios"
  tasks:
    - name: BUILD CONFIGS
      template:
        src=templates/Routers.j2
        dest=configs/{{inventory_hostname }}.conf
    - name: PUSH CONFIGS
      napalm_install_config:
        hostname={{ inventory_hostname }}
        username={{ un }}
        password={{ pwd }}
        dev_os={{ os }}
        config_file=configs/{{ inventory_hostname }}.conf
        commit_changes=1
        replace_config=0
